### ISSUE TITLE
Add new route with login for The Distraction Shield

### ISSUE THREAD

**Issue by martinavagyan** [mircealungu/practice-as-a-service#13]

**Comment by mircealungu** [comment]
Rather than a new route, this is more a cross-cutting concern to all your existing routes. Something like the @with_user or @with_session in Zeeguu where if the user is not logged in, you simply redirect them to the zeeguu.unibe.ch/login. 

Ah, but you need to also come back... so probably we need to add a with_comeback parameter to that route, so we're sure the user is redirected to the exercises once he's logged in.

**Comment by martinavagyan** [comment]
That's true, I will have a look into that and try to come up with consistent solution.
