### ISSUE TITLE
Bookmarks cross origin error 

### ISSUE THREAD

**Issue by martinavagyan** [mircealungu/practice-as-a-service#77]
@mircealungu From time to time I get this error, it does not seem to follow any pattern. 
![image](https://cloud.githubusercontent.com/assets/7386708/26832037/6b0ff902-4ace-11e7-9854-39e959feb085.png)
In Postman I get this:
![image](https://cloud.githubusercontent.com/assets/7386708/26832151/da1fe276-4ace-11e7-833a-e760ab233319.png)

**Comment by mircealungu** [comment]
Thanks Martin!

You seem to always get the access-control error when there's a bug in the
server.

For some reason, the server was crashing since you had two bookmarks
which were saved in the DB w/o translation and the code expects that there's
always a translation.

I've fixed the DB. I've also added a constraint on the DB table, so we
should
not get in this state again.

M.
